language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=REL1_30; TYPE=coverage
      php: 5.6
    - env: DB=sqlite; MW=REL1_27; SITELANG=ja
      php: 5.5
    - env: DB=sqlite; MW=master; PHPUNIT=4.8.*
      php: 7.1
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
     - env: DB=sqlite; MW=master; PHPUNIT=4.7.*

install:
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-external-query-lookup.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
